### ISSUE TITLE
Object reference not set to an instance of an object for the template help for some resources.

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-templates#1014]
I'm implementing the template, and found that `dotnet new TEMPLATE --help` will fails for some template. 
It works for cosmos but not for `rqueue`  and `kafka` (this is on the PR branch)

```
dotnet new rqueue --help
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --interactive       Allows the internal dotnet restore command to stop and wait for user input or action (for example to complete authentication).
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates.


RabbitMQTrigger (C#)
Author: Microsoft
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.FindBestHostTemplateConfigFile(IFileSystemInfo config)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.LoadTemplate(ITemplateInfo info, String baselineName)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateUsageHelp.GetTemplateUsageInformation(ITemplateInfo templateInfo, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateDetailsDisplay.DetermineParameterDispositionsForTemplateGroup(IReadOnlyList`1 templateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateDetailsDisplay.ShowTemplateGroupHelp(IReadOnlyCollection`1 templateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator, Boolean showImplicitlyHiddenParams)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.TemplateDetailedHelpForSingularTemplateGroup(IReadOnlyCollection`1 unambiguousTemplateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.DisplayHelpForUnambiguousTemplateGroup(ListOrHelpTemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator, ITelemetryLogger telemetryLogger, String defaultLanguage)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.CoordinateHelpAndUsageDisplay(ListOrHelpTemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, ITelemetryLogger telemetryLogger, TemplateCreator templateCreator, String defaultLanguage, Boolean showUsageHelp)
   at Microsoft.TemplateEngine.Cli.New3Command.EnterTemplateManipulationFlowAsync()
   at Microsoft.TemplateEngine.Cli.New3Command.ExecuteAsync()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

**Comment by TsuyoshiUshio** [comment]
Move to https://github.com/dotnet/templating/issues/2790
