### ISSUE TITLE
Errors show up after adding a Blob trigger function on Azure Function V2 Project with "Microsoft.NET.Sdk.Functions" verison 1.0.21 : "Metadata generation failed.".

### ISSUE THREAD

**Issue by phenning** [Azure/azure-functions-templates#749]
With latest 15.9 preview:

1. File > New Project > Azure Functions >Azure Functions v2 (.Net Core) with Empty template + Storage Emulator selected.
2.Open Manage Nuget Packages to update the "Microsoft.NET.Sdk.Functions" verison to 1.0.21
3. Right click project -> Add New Item-> New Azure Function...
4.Select the Blob trigger function and set the connection to "AzureWebJobsStorage".Click OK. 
5. Build.

Then, errors shows up in the error list.

ACTUAL
![function2](https://user-images.githubusercontent.com/2433750/45768516-f8c56a80-bbf1-11e8-8269-572419a5d2a9.png)

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | System.IO.FileNotFoundException: Could not load file or   assembly 'Microsoft.Azure.WebJobs, Version=3.0.0.0, Culture=neutral,   PublicKeyToken=null' or one of its dependencies. The system cannot find the   file specified.File name: 'Microsoft.Azure.WebJobs, Version=3.0.0.0,   Culture=neutral, PublicKeyToken=null'     at System.ModuleHandle.ResolveType(RuntimeModule module, Int32   typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs,   Int32 methodInstCount, ObjectHandleOnStack type)   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule   module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext,   RuntimeTypeHandle[] methodInstantiationContext)   at System.Reflection.RuntimeModule.ResolveType(Int32   metadataToken, Type[] genericTypeArguments, Type[]   genericMethodArguments)   at   System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord   caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly,   RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType   attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList   derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo&   ctor, Boolean& ctorHasParameters, Boolean& isVarArg)   at   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule   decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType   attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes,   Boolean isDecoratedTargetSecurityTransparent)   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeParameterInfo   parameter, RuntimeType caType)   at   System.Attribute.InternalParamGetCustomAttributes(ParameterInfo param, Type   type, Boolean inherit)   at   MakeFunctionJson.ParameterInfoExtensions.GetDisabledAttribute(ParameterInfo   parameterInfo)   at   System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()   at   System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()   at   System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)   at MakeFunctionJson.MethodInfoExtensions.GetDisabled(MethodInfo   method)   at   MakeFunctionJson.MethodInfoExtensions.HasUnsuportedAttributes(MethodInfo   method, String& error)   at   MakeFunctionJson.FunctionJsonConverter.<GenerateFunctions>d__9.MoveNext()   at System.Collections.Generic.List`1..ctor(IEnumerable`1   collection)   at   System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   at   MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()   at   MakeFunctionJson.FunctionJsonConverter.TryRun()WRN: Assembly binding logging   is turned OFF.To enable assembly bind failure logging, set the registry value   [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.Note: There is some   performance penalty associated with assembly bind failure logging.To turn   this feature off, remove the registry value   [HKLM\Software\Microsoft\Fusion!EnableLog].Error generating functions   metadata | FunctionApp6 | C:\Users\v-lingyx\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets | 39 |  
Error |   | Metadata generation failed. | FunctionApp6 | C:\Users\v-lingyx\.nuget\packages\microsoft.net.sdk.functions\1.0.21\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets | 39 |

**Comment by Andy-Win** [comment]
With latest 15.9 preview4(d15.9stg.28210.3005)

1.File > New Project > Azure Functions >Azure Functions **v1** (.Net framework) with Empty template + Storage Emulator selected.
2.Open Manage Nuget Packages to update the "Microsoft.NET.Sdk.Functions" verison to **1.0.23**
3.Right click project -> Add New Item-> New Azure Function...
4.Select the Http trigger function .Click OK.
5.Build.

Then the same errors shows up. not repro with Azure Functions **v2** (.Net Core)

**Actual**

**System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.NET.Sdk.Functions, Version=1.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.**
File name: 'Microsoft.NET.Sdk.Functions, Version=1.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at MakeFunctionJson.FunctionJsonSchema..ctor()
   at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodInfo method, String assemblyPath)
   at MakeFunctionJson.FunctionJsonConverter.<GenerateFunctions>d__9.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Error generating functions metadata

**Metadata generation failed**.

**Comment by Jessiexly** [comment]
Only on Dev15.7.6 and Dev15.6.7
Same steps except updating the "Microsoft.NET.Sdk.Functions" verison to 1.0.23, build with errors:

It was not possible to find any compatible framework version 
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found. 
  - Check application dependencies and target a framework version installed at: 
      \ 
  - Alternatively, install the framework version '2.1.0'. 

Metadata generation failed.
![image](https://user-images.githubusercontent.com/31506385/47061522-66ba7d00-d204-11e8-8444-2cce023f90cc.png)

**Comment by pconnell99** [comment]
Same (or similar) here for a V1 project (I'm a javascript dev so this is all new to me).  Brand new Functions v1 with target platform net461.  Trying to build shows:-

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.NET.Sdk.Functions, Version=1.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.NET.Sdk.Functions, Version=1.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at MakeFunctionJson.FunctionJsonSchema..ctor()
   at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodInfo method, String assemblyPath)
   at MakeFunctionJson.FunctionJsonConverter.<GenerateFunctions>d__9.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Error generating functions metadata
	Project.Projectname	C:\Users\xxxxxx\.nuget\packages\microsoft.net.sdk.functions\1.0.23\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets	41	
```

**Comment by jasonrmartin** [comment]
I have the same issue.  Switching back to Microsoft.NET.Sdk.Function v1.0.22 fixed for me.

**Comment by davidrevoledo** [comment]
Same here and back to `Microsoft.NET.Sdk.Function v1.0.22` worked, there is a problem with 1.0.23?
